version: "3"

networks:
  gitea_network:

services:
  gitea:
    image: gitea/gitea
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - APP_NAME=$APP_NAME
      - GITEA__server__DOMAIN=$GITEA_DOMAIN
      - GITEA__server__ROOT_URL=$GITEA_ROOT_URL
      - GITEA__server__HTTP_ADDR=localhost
      - GITEA__server__HTTP_PORT=3000
      - GITEA__server__LANDING_PAGE=login
      - GITEA__admin__DISABLE_REGULAR_ORG_CREATION=true
      - GITEA__repository__FORCE_PRIVATE=true
      - GITEA__repository__DEFAULT_PRIVATE=private
      - GITEA__repository__DEFAULT_PUSH_CREATE_PRIVATE=true
      - GITEA__repository__DEFAULT_BRANCH=main
      - GITEA__repository__DISABLE_MIGRATIONS=true
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=$POSTGRES_DB
      - GITEA__database__USER=$POSTGRES_USER
      - GITEA__database__PASSWD=$POSTGRES_PASSWORD
      - GITEA__service__DEFAULT_USER_VISIBILITY=private
      - GITEA__service__ALLOWED_USER_VISIBILITY_MODES=private
      - GITEA__service__DEFAULT_ORG_VISIBILITY=private
      - GITEA__service__ALLOW_ONLY_INTERNAL_REGISTRATION=true
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service__REQUIRE_SIGNIN_VIEW=true
      - GITEA__service__DEFAULT_ALLOW_CREATE_ORGANIZATION=false
      - GITEA__service.explore__REQUIRE_SIGNIN_VIEW=true
      - GITEA__service.explore__DISABLE_USERS_PAGE=true
      - GITEA__openid__ENABLE_OPENID_SIGNUP=false
      - GITEA__openid__ENABLE_OPENID_SIGNIN=false
      - GITEA__oauth2__ENABLE=false
      - GITEA__federation__ENABLE=false
      - GITEA__mirror__ENABLE=false
      - GITEA__other__SHOW_FOOTER_BRANDING=false
      - GITEA__other__SHOW_FOOTER_VERSION=false
      - GITEA__other__SHOW_FOOTER_TEMPLATE_LOAD_TIME=false
      - GITEA__api__ENABLE_SWAGGER=false
    depends_on:
      - postgres
    networks:
      - gitea_network
    restart: always
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "$GITEA_PORT:3000"
      - "$GITEA_SSH_PORT:22"

  postgres:
    image: postgres:alpine
    container_name: gitea_postgres
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    networks:
      - gitea_network
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
