#!/usr/bin/env bash

script_name="$(basename "$0")"
script_dir="$(realpath "$(dirname "$0")")"

root_dir="$(realpath "$script_dir/..")"

env_file="$root_dir/.env"
docker_compose_file="$root_dir/docker-compose.yml"

usage() {
  echo "$script_name: usage: $script_name FILENAME" >&2
}

exit_with_error() {
  echo "$script_name: error: $1" >&2
  usage
  exit 1
}

load_env() {
  IFS=$'\n'
  # shellcheck disable=SC2046
  export $(grep -Ev '^#' "$env_file" | xargs -0)
  IFS=
}

if [ "$#" != "1" ]; then
  exit_with_error "invalid number of arguments $#"
fi

if ! [ -f "$env_file" ]; then
  exit_with_error "$env_file not found"
fi

load_env

filepath="$1"

docker-compose -f "$docker_compose_file" \
  exec -u 1000 \
  gitea gitea dump \
  --file="-" \
  --type="tar.gz" \
  --config="/data/gitea/conf/app.ini" >"$filepath"
